// flow-typed signature: 4132540e44057cac1823e38fc9ece51a
// flow-typed version: <<STUB>>/babel-plugin-react-intl_v3.5.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-intl/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/dist/print-icu-message' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/lib/print-icu-message' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-intl/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/dist/index'>;
}
declare module 'babel-plugin-react-intl/dist/print-icu-message.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/dist/print-icu-message'>;
}
declare module 'babel-plugin-react-intl/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/lib/index'>;
}
declare module 'babel-plugin-react-intl/lib/print-icu-message.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/lib/print-icu-message'>;
}
