// flow-typed signature: 10a5e80223e1b5064c66aa3c2a5ec3e9
// flow-typed version: <<STUB>>/modify-babel-preset_v3.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modify-babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'modify-babel-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modify-babel-preset/lib/flatten' {
  declare module.exports: any;
}

declare module 'modify-babel-preset/lib/normalize-preset' {
  declare module.exports: any;
}

declare module 'modify-babel-preset/lib/serialize' {
  declare module.exports: any;
}

declare module 'modify-babel-preset/test/fixtures/two/index' {
  declare module.exports: any;
}

declare module 'modify-babel-preset/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'modify-babel-preset/index' {
  declare module.exports: $Exports<'modify-babel-preset'>;
}
declare module 'modify-babel-preset/index.js' {
  declare module.exports: $Exports<'modify-babel-preset'>;
}
declare module 'modify-babel-preset/lib/flatten.js' {
  declare module.exports: $Exports<'modify-babel-preset/lib/flatten'>;
}
declare module 'modify-babel-preset/lib/normalize-preset.js' {
  declare module.exports: $Exports<'modify-babel-preset/lib/normalize-preset'>;
}
declare module 'modify-babel-preset/lib/serialize.js' {
  declare module.exports: $Exports<'modify-babel-preset/lib/serialize'>;
}
declare module 'modify-babel-preset/test/fixtures/two/index.js' {
  declare module.exports: $Exports<'modify-babel-preset/test/fixtures/two/index'>;
}
declare module 'modify-babel-preset/test/index.js' {
  declare module.exports: $Exports<'modify-babel-preset/test/index'>;
}
